# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: compare-packages

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/compare-packages
        id: compare-packages
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ${{ steps.compare-packages.outputs.RESULTS }}"
